import Head from 'next/head'
import Landing from './CMP/Landing'
import { useEffect, useState } from 'react'
import Navbar from './Navbar'

export default function Home() {
  const [Hovered, setHovered] = useState(false)
  useEffect(() => {
  
 const hover=document.querySelectorAll('#hovered')

 for (let index = 0; index <150 ;index++) {
   hover[index]?.addEventListener("mouseover",()=>{
    setHovered(prev=>prev=true)
   });
   hover[index]?.addEventListener("mouseout",()=>{
    setHovered(prev=>prev=false)
   })
 }
 
  }, [])
  console.log(Hovered);
  
  return (
    <div style={{
      backgroundImage: `url(https://media.istockphoto.com/id/526151656/photo/sand-dune-45-in-sossusvlei-namibia.jpg?s=170667a&w=0&k=20&c=TXOInnvZjP-d8_wNjhw-lc2Sp7JqBHO2gt3hM7FKlrs=)`,
 
    }}
    className='h-[100vh] w-[100vw] bg-cover bg-center '
    onMouseMove={(e)=>{ 
      const cursor=document.getElementById("Mouse")
      const x=e.clientX
      const y=e.clientY
      if(cursor != null)
     { cursor.style.left=x+"px";
     cursor.style.top=y+"px";
   }
     }} 
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div  id='Mouse' className={` w-1 h-1 p-3 absolute rounded-full border-2 border-solid border-[#33333389] 
      translate-x-[-50%] translate-y-[-50%] bg-[transparent] ${Hovered && "border-[transparent] "} `}>
 <div   id='Mouse' 
 className={`absolute bg-black rounded-full w-[6px] h-[6px] translate-x-[-50%] translate-y-[-50%] 
 ${Hovered && "h-[75px] bg-[#3333338e] w-[75px] "}  duration-500 `}  > </div>
      </div>

      <Navbar></Navbar>
      <Landing ></Landing>
     
    </div>
  )
}
